# ==== Preprocessing ==== #
preproc_name: init

thingsmeg_dir: /mnt/tsukuyomi/things-meg/
meg_dir: ${thingsmeg_dir}derivatives/preprocessed/

things_dir: /mnt/tsukuyomi/things/osfstorage/THINGS/
images_dir: ${things_dir}Images/
metadata_dir: ${things_dir}Metadata/
preprocessed_data_dir: data/preprocessed/thingsmeg/

# segment_in_preproc: True

# max_seq_len: 0.5 # This value CANNOT be changed from 0.5.

# brain_filter_low: 0.1 # Hz
# brain_filter_high: 250 # Hz
brain_resample_sfreq: 120 # Hz
# clamp_lim: 4.0 # Standard deviation
# baseline_ratio: -0.1 # Ratio compared to max_seq_len. Negative value means to take signals before stimulus onset.


# ==== Training ==== #
project_name: nd_things_clip
train_name: large_test
# debug: False

# seq_onset: 0.0
seq_len: 1.41 # Original number of samples at 200Hz is 281, and 169 at 120Hz.

dataset: ThingsMEG
# image_size: 256

montage_path: brain2face/utils/montages/things_meg.npy
layout: ch_locations_2d # DynamicChanLoc2d

spatial_attention: True

F: 768 # CLIP embedding dimension

reduce_time: True

vision:
  pretrained: True
  model: ViT # For face.pretrained=False
  pretrained_model: ViT-L/14 # For face.pretrained=True
  encoded: False # False is basically only for StyleGAN
  
vision_encoder:
  image_size: ${image_size}
  patch_size: 32
  dim: ${F}
  depth: 6
  heads: 16
  mlp_dim: 2048
  dropout: 0.1
  emb_dropout: 0.1

D1: 270
D2: 320
K: 32
d_drop: 0.3 # Dropout rate for spatial-attention
p_drop: 0.1 # Dropout rate for conv blocks
num_conv_blocks: 2
downsample: False # Can be a list of bools with length num_conv_blocks
final_ksize: 1
final_stride: 1
temporal_aggregation: affine # original or affine or pool. This is somewhat overlapping with reduce_time, but this is for model and reduce_time is for data.
head_activation: True
ksizes:
  conv_block: 3
biases:
  conv_block: True
  conv_subj_sa: True
  linear_reduc_time: True

vq_brain: False
vq:
  type: raw # raw or (temporally) aggregated 
  num_embeds: 256
  num_concepts: 8 # Only for aggregated vq. Should correspond to the minimal number of concepts to explain an image with text.
  alpha: 1.0 # How much to weight regularization terms against CLIP loss.
  beta: 0.25 # How much to weight encoder regularization term against codebook loss.

large_test_set: True

batch_size: 128
lr: 0.005
lr_scheduler: cosine # cosine or multistep
lr_multistep_mlstns: [0.4, 0.6, 0.8, 0.9]
lr_step_gamma: 0.5
epochs: 300 # 500
reduction: mean
clip_temp:
  init: 5.0
  learn: True
  min: 0.1
  max: 10.0

acc_topk: [1, 5]

accum_grad: False

chance: False

test_with_whole: True

num_workers: 8

seed: 1234

cuda_id: 1

sweep_count: 3
sweep_config:
  method: grid
  metric:
    name: test_top10_acc
    goal: maximize
  parameters:
    # temporal_aggregation:
    #   values: [original]
    # downsample:
    #   values: [False]
    # split:
    #   values: [mixed_shallow, mixed_deep]
    # ksizes.conv_block:
    #   values: [3, 5, 7]
    # d_drop:
    #   values: [0.4]
    # seq_onset:
    #   values: [0.0, 0.5, 1.0, 1.5]
    # seq_len:
    #   values: [0.5, 0.3, 0.1]
    # layout:
    #   values: [DynamicChanLoc2d, ch_locations_2d]
    p_drop:
      values: [0.1, 0.2, 0.3]
    # vq_brain:
    #   values: [False, True]
    # vq.type:
    #   values: [aggregated]
    # vq.num_embeds:
    #   values: [64, 256, 16]
    # vq.alpha:
    #   values: [0.001, 0.01, 0.1]
    # vq.beta:
    #   values: [0.25, 1.0]
    # learn_temperature:
    #   values: [False]
    # biases.conv_block:
    #   values: [True, False]
    # biases.conv_subj_sa:
    #   values: [True, False]
    # biases.linear_reduc_time:
    #   values: [True, False]

# ==== Evaluation ==== #
eval:
  seq_len: 0.5

as_h5: True
for_webdataset: False