preproc_name: 1_paper

thingsmeg_dir: /mnt/tsukuyomi/things-meg/
preprocessed_data_dir: data/preprocessed/thingsmeg/
clip_embeds_dir: data/clip_embds/thingsmeg/

# CLIP
large_test_set: True
eval:
  pos_enc: sine_rel
  # vq: null

dataset: ThingsMEG
train_name: large_test
clip_train_name: test
type: image

unet1:
  dim: 128
  dim_mults: [1, 2, 4, 8]

unet2:
  dim: 16
  dim_mults: [1, 2, 4, 8, 16]

image_embed_dim: 768
channels: 3

image_sizes: [128, 256] # First Unet up to 128px, then Unet up to 256px

timesteps: 1000

epochs: 800
batch_size: 16
accum_grad: False
lr: 3.0e-4
wd: 1.0e-2
ema_beta: 0.99
ema_update_after_step: 1000
ema_update_every: 10

cuda_id: 0
num_workers: 64
seed: 1234
log_level: INFO

use_wandb: False
wandb:
  project: nd_things_decoder
  entity: sensho