# ==== Preprocessing ==== #
preproc_name: drop-epilepsy

data_root: /storage/dataset/ECoG/internal/GODv2-4/
freesurfer_dir: /storage/data/freesurfer/Subject_ECoG/

segment_in_preproc: True

max_seq_len: 0.5 # This value CANNOT be changed from 0.5.

brain_filter_low: 0.1 # Hz
brain_filter_high: 250 # Hz
brain_resample_sfreq: 500 # Hz
clamp_lim: 4.0 # Standard deviation
baseline_ratio: -0.1 # Ratio compared to max_seq_len. Negative value means to take signals before stimulus onset.


# ==== Training ==== #
project_name: nd_god_clip
train_name: vq
debug: False

seq_onset: 0.0
seq_len: 0.5

dataset: YLabGOD
image_size: 256

montage_dir: brain2face/utils/montages/GOD/
layout: DynamicChanLoc2d
loc_random: False

spatial_attention: True

F: 512 # CLIP embedding dimension

reduce_time: True # For GOD dataset, time is already reduced.

vision:
  pretrained: True
  model: ViT # For face.pretrained=False
  pretrained_model: ViT-B/32 # For face.pretrained=True
  encoded: False # False is basically only for StyleGAN
  
vision_encoder:
  image_size: ${image_size}
  patch_size: 32
  dim: ${F}
  depth: 6
  heads: 16
  mlp_dim: 2048
  dropout: 0.1
  emb_dropout: 0.1

D1: 270
D2: 320
K: 32
d_drop: 0.3
num_conv_blocks: 5
downsample: [True, True, True, True, True] # Length must be num_conv_blocks.
final_ksize: 1
final_stride: 1
head_activation: True
time_multiplier: 1
ksizes:
  conv_block: 3
biases:
  conv_block: True
  conv_subj_sa: True
  linear_reduc_time: True

vq_brain: True
vq:
  num_embeds: 64
  beta: 0.25

split: rep_or_part # none or mixed_deep or mixed_shallow or rep_or_part
# Split is predefined as different sessions for ECoG GOD dataset, but
# mixed_deep first mixes train and val, then splits them deeply.
train_ratio: 0.8
batch_size: 64
lr: 0.005
lr_scheduler: multistep # cosine or multistep
lr_multistep_mlstns: [0.4, 0.6, 0.8, 0.9]
lr_step_gamma: 0.5
epochs: 2000
reduction: mean
init_temperature: 5.0
learn_temperature: True

accum_grad: False

chance: False

test_with_whole: False

num_workers: 4

seed: 1234

cuda_id: 0

sweep_count: 1
sweep_config:
  method: grid
  metric:
    name: test_top10_acc
    goal: maximize
  parameters:
    # split:
    #   values: [mixed_shallow, mixed_deep]
    # ksizes.conv_block:
    #   values: [3, 5, 7]
    # d_drop:
    #   values: [0.4]
    # seq_onset:
    #   values: [0.0, 0.5, 1.0, 1.5]
    # seq_len:
    #   values: [0.5, 0.3, 0.1]
    # layout:
    #   values: [DynamicChanLoc2d, ch_locations_2d]
    # vq_brain:
    #   values: [False]
    # vq.num_embeds:
    #   values: [64, 256, 16]
    learn_temperature:
      values: [False]
    # biases.conv_block:
    #   values: [True, False]
    # biases.conv_subj_sa:
    #   values: [True, False]
    # biases.linear_reduc_time:
    #   values: [True, False]

# ==== Evaluation ==== #
eval:
  seq_len: 0.5

as_h5: True
for_webdataset: False