dataset: YLabGOD

dim: 512
depth: 6
dim_head: 64
heads: 8

image_embed_dim: 512
timesteps: 100
cond_drop_prob: 0.2

epochs: 500
# train_ratio: 0.8
batch_size: 64
lr: 3.0e-4
wd: 1.0e-2
ema_beta: 0.99
ema_update_after_step: 1000
ema_update_every: 10

cuda_id: 1
seed: 1234

use_wandb: True
wandb:
  project: diffusion_prior
  entity: sensho
  run_name: god_test


lr_scheduler: none # cosine or multistep or none
lr_multistep_mlstns: [0.4, 0.6, 0.8, 0.9]
lr_step_gamma: 0.5