dataset: UHD
train_name: unet3d
clip_train_name: unet3d
type: video
temporal_emb: False

dim: 512
depth: 6
dim_head: 64
heads: 8

image_embed_dim: 512
timesteps: 100
cond_drop_prob: 0.2

epochs: 50
# train_ratio: 0.8
batch_size: 128 # For embs with temporal dimension, batch_size is multiplied by timesteps.
lr: 3.0e-4
wd: 1.0e-2
ema_beta: 0.99
ema_update_after_step: 1000
ema_update_every: 10

cuda_id: 2
seed: 1234

use_wandb: False
wandb:
  project: nd_uhd_prior
  entity: sensho


lr_scheduler: none # cosine or multistep or none
lr_multistep_mlstns: [0.4, 0.6, 0.8, 0.9]
lr_step_gamma: 0.5