unet1:
  dim: 128
  dim_mults: [1, 2, 4, 8]

unet2:
  dim: 16
  dim_mults: [1, 2, 4, 8, 16]

image_embed_dim: 512
channels: 3

image_sizes: [256, 256]

timesteps: 1000

lr: 3.0e-4
wd: 1.0e-2
ema_beta: 0.99
ema_update_after_step: 1000
ema_update_every: 10

cuda_id: 1
seed: 1234

use_wandb: True
wandb:
  project: decoder_uhd
  entity: sensho
  run_name: test