run_name: test

dataset: UHD

dim: 512
depth: 6
dim_head: 64
heads: 8

image_embed_dim: 512
timesteps: 100
cond_drop_prob: 0.2

epochs: 20
batch_size: 128
lr: 3.0e-4
wd: 1.0e-2
ema_beta: 0.99
ema_update_after_step: 1000
ema_update_every: 10

cuda_id: 0
seed: 1234

use_wandb: True
wandb:
  project: diffusion_prior_uhd
  entity: sensho