dataset: UHD

dim: 512
depth: 6
dim_head: 64
heads: 8

image_embed_dim: 512
timesteps: 100
cond_drop_prob: 0.2

train_ratio: 0.8
batch_size: 32
lr: 1.1e-4
lr_scheduler: multistep # cosine or multistep
lr_multistep_mlstns: [0.4, 0.6, 0.8, 0.9]
lr_step_gamma: 0.5
epochs: 500

cuda_id: 0
seed: 1234

use_wandb: True
wandb:
  project: diffusion_prior_uhd
  entity: sensho
  run_name: test