# ==== Dataset ==== #
dataset: ArayaDriving
data_root: /mnt/neurotech_nas/driving-game/ # /home/sensho/brain2face/assets/example_data/

# ==== Preprocess ==== #
# Common
preproc_name: test_subj_names
seq_len: 3 # segment length in seconds
subject_multiprocess: False
start_subj: 0
end_subj: 8
debug: False

face_extractor:
  mode: mesh
  output_size: [256, 256]
  eyes_dist_mult: 4
  movement_alert_thresh: 50 # px

stylegan:
  model_path: /home/sensho/brain2face/encoder4editing/weights/e4e_ffhq_encode.pt

# Face
eye_half: 16 # number of pixels
fps: 30
image_size: 32

# Brain
brain_resample_rate: 120 # Hz
brain_filter_low: 1.0 # Hz
brain_filter_high: 60 # Hz
clamp_lim: 20 # values after robust scaling
baseline_len: 0.5 # sec
shift_brain: False
shift_len: 150 # ms


# ==== Training ==== #
train_name: deep

split: deep # shallow / deep / subject_random / subject_each
# subject_random: picks 20% sessions for test, without considering subjects' identity
# subject_each: each subject has one or two test sessions (currently not working)

train_ratio: 0.8
chance: False
# 🔥 FIXME: with too large a batchsize there isn't enough 
# 🔥 FIXME: samples in the eval set, and the CLIPLoss produces nans silently
batch_size: 64
lr: 0.005
lr_scheduler: cosine # cosine or multistep
lr_multistep_mlstns: [0.4, 0.6, 0.8, 0.9]
lr_step_gamma: 0.5
epochs: 500
reduction: mean
init_temperature: 5.0

cuda_id: 0

use_wandb: False


# ==== Architecture ==== #
# Common
F: 512 # 1024

# Brain
D1: 270
D2: 320
K: 32
d_drop: 0.3 # Channel distance for spatial dropout
# NOTE: setting these 2 is the key that BrainEncoder downsamples EEG from 120Hz to 30Hz
final_kernel_size: 2
final_stride: 2

# Face (ViViT)
patch_size: 8
depth: 2

seed: 1234