# ==== Preprocessing ==== #
preproc_name: test
debug: False

data_root: /mnt/tsukuyomi/uhd-eeg/
# ica_data_root: /home/sensho/brain2face/driving_ica/
start_subj: 0
end_subj: 8

seq_len: 3 # segment length in seconds

# ---- Face ---- #
fps: 30

face_extractor:
  mode: mesh
  output_size: [256, 256]
  eyes_dist_mult: 4
  movement_alert_thresh: 50 # px

# stylegan:
#   model_path: /home/sensho/brain2face/encoder4editing/weights/e4e_ffhq_encode.pt

# ---- Brain ---- #
brain_orig_sfreq: 250 # Hz
brain_resample_sfreq: 120 # Hz
brain_filter_low: 1.0 # Hz
brain_filter_high: 60 # Hz
clamp_lim: 20 # values after robust scaling
baseline_len: 0.5 # sec
shift_brain: False
shift_len: 150 # ms

eeg_load_bufsize: 1000 # samples


# ==== Training ==== #
train_name: deep

dataset: Brain2FaceStyleGANDataset

split: deep # shallow / deep / subject_random / subject_each
# subject_random: picks 20% sessions for test, without considering subjects' identity
# subject_each: each subject has one or two test sessions (currently not working)

train_ratio: 0.8
chance: False
# 🔥 FIXME: with too large a batchsize there isn't enough 
# 🔥 FIXME: samples in the eval set, and the CLIPLoss produces nans silently
batch_size: 64
lr: 0.005
lr_scheduler: cosine # cosine or multistep
lr_multistep_mlstns: [0.4, 0.6, 0.8, 0.9]
lr_step_gamma: 0.5
epochs: 500
reduction: mean
init_temperature: 5.0

cuda_id: 0

use_wandb: False


# ==== Architecture ==== #
# Common
F: 512 # 1024

# Brain
D1: 270
D2: 320
K: 32
d_drop: 0.3 # Channel distance for spatial dropout
# NOTE: setting these 2 is the key that BrainEncoder downsamples EEG from 120Hz to 30Hz
final_kernel_size: 2
final_stride: 2

# Face (ViViT)
patch_size: 8
depth: 2

seed: 1234