run_name: test
type: video
dataset: UHD

unet1:
  dim: 128
  dim_mults: [1, 2, 4, 8]

unet2:
  dim: 16
  dim_mults: [1, 2, 4, 8, 16]

image_embed_dim: 512
channels: 3

frame_sizes: [128, 256] # First Unet up to 128px, then Unet up to 256px
frame_numbers: [90, 90] # Not doing temporal super-resolution for now

timesteps: 1000

epochs: 20
batch_size: 1
lr: 3.0e-4
wd: 1.0e-2
ema_beta: 0.99
ema_update_after_step: 1000
ema_update_every: 10

cuda_id: 0
seed: 1234

use_wandb: False
wandb:
  project: decoder_uhd
  entity: sensho