# ==== Preprocessing ==== #
preproc_name: init

data_root: /storage/dataset/ECoG/internal/GODv2-4/

segment_in_preproc: True

brain_filter_low: 0.1 # Hz
brain_filter_high: 250 # Hz
brain_resample_sfreq: 500 # Hz
clamp_lim: 20
baseline_ratio: 0.2 # ratio compared to 0.5 seconds


# ==== Training ==== #
project_name: neuro-diffusion_god
train_name: test

dataset: YLabGOD
image_size: 256

montage_dir: brain2face/utils/montages/GOD/

F: 256 # CLIP embedding dimension

D1: 270
D2: 320
K: 32
d_drop: 0.3
final_ksize_stride: 2
head_activation: True

split: none # split is predefined since experiment for this dataset
train_ratio: 0.8
batch_size: 64
lr: 0.005
lr_scheduler: multistep # cosine or multistep
lr_multistep_mlstns: [0.4, 0.6, 0.8, 0.9]
lr_step_gamma: 0.5
epochs: 500
reduction: mean
init_temperature: 5.0

chance: False

test_with_whole: False

seed: 1234

cuda_id: 0