dataset: UHD
train_name: no-ema
clip_train_name: unet3d
type: video
temporal_emb: False

unet1:
  dim: 64
  dim_mults: [1, 2, 4, 8]

unet2:
  dim: 8
  dim_mults: [1, 2, 4, 8, 16]

video_embed_dim: 512
channels: 3

frame_sizes: [64, 128] # First Unet up to 128px, then Unet up to 256px
frame_numbers: [90, 90] # Not doing temporal super-resolution for now

timesteps: 1000

epochs: 50
batch_size: 2 # 64

decoder_trainer:
  lr: 3.0e-4
  wd: 1.0e-2
  use_ema: False
  ema_beta: 0.99
  ema_update_after_step: 1000
  ema_update_every: 10

cuda_id: 1
seed: 1234
log_level: INFO

use_wandb: False
wandb:
  project: nd_uhd_video-decoder
  entity: sensho

deepspeed:
  gradient_accumulation_steps: 32